services:

  api:
    build: .
    container_name: stock_exchange_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: stock_exchange_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stock_exchange
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: stock_exchange_redis
    ports:
      - "6379:6379"
volumes:
  postgres_data: